# Generated by Django 4.2.4 on 2023-08-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="beautician",
            name="services",
            field=models.ManyToManyField(to="beautician.services"),
        ),
    ]
