# Generated by Django 4.2.4 on 2023-09-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0002_services_beautician_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="beautician",
            name="image",
            field=models.ImageField(default=1, upload_to=""),
            preserve_default=False,
        ),
    ]
