# Generated by Django 4.2.4 on 2023-09-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0005_alter_beautician_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beautician",
            name="image",
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
