# Generated by Django 4.2.4 on 2023-09-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0006_alter_beautician_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="image",
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
    ]
