# Generated by Django 4.2.4 on 2023-09-10 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0007_services_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="beautician",
            name="expertin",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beauticians_expert_in",
                to="beautician.services",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="beautician",
            name="services",
            field=models.ManyToManyField(
                related_name="beauticians_providing_services", to="beautician.services"
            ),
        ),
    ]
