# Generated by Django 4.2.4 on 2023-09-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0009_alter_beautician_expertin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="image",
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
