# Generated by Django 4.2.4 on 2023-09-13 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0011_alter_beautician_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blockeddate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "beautician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="beautician.beautician",
                    ),
                ),
            ],
        ),
    ]
