# Generated by Django 4.2.4 on 2023-09-14 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0012_blockeddate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Studio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locality", models.CharField(max_length=200)),
                ("place", models.CharField(max_length=200)),
                ("district", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                (
                    "beautician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="beautician.beautician",
                    ),
                ),
            ],
        ),
    ]
