# Generated by Django 4.2.4 on 2023-09-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0013_studio"),
    ]

    operations = [
        migrations.AddField(
            model_name="beautician",
            name="isblocked",
            field=models.BooleanField(default=False),
        ),
    ]
