# Generated by Django 4.2.4 on 2023-09-17 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0015_alter_beautician_isblocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="beautician",
            name="expertin_fee",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Servicefees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("servicefee", models.PositiveIntegerField()),
                ("blocked", models.BooleanField(default=False)),
                (
                    "beautician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="beautician.beautician",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="beautician.services",
                    ),
                ),
            ],
        ),
    ]
