# Generated by Django 4.2.4 on 2023-09-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0016_beautician_expertin_fee_servicefees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicefees",
            name="servicefee",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
