# Generated by Django 4.2.4 on 2023-09-18 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0017_alter_servicefees_servicefee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beautician",
            name="services",
        ),
    ]
