# Generated by Django 4.2.4 on 2023-09-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0018_remove_beautician_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beautician",
            name="expertin_fee",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
