# Generated by Django 4.2.4 on 2023-09-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0019_alter_beautician_expertin_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="studio",
            name="country",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studio",
            name="pincode",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
