# Generated by Django 4.2.4 on 2023-09-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0020_studio_country_studio_pincode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beautician",
            name="expertin",
        ),
        migrations.RemoveField(
            model_name="beautician",
            name="expertin_fee",
        ),
        migrations.AddField(
            model_name="servicefees",
            name="topservice",
            field=models.BooleanField(default=False),
        ),
    ]
