# Generated by Django 4.2.4 on 2023-09-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0021_remove_beautician_expertin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
