# Generated by Django 4.2.4 on 2023-10-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0025_studio_studio_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="beautician",
            name="appointment_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
