# Generated by Django 4.2.4 on 2023-10-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0026_beautician_appointment_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beautician",
            name="appointment_count",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
