# Generated by Django 4.2.4 on 2023-10-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0027_alter_beautician_appointment_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beautician",
            name="appointment_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
