# Generated by Django 4.2.4 on 2023-10-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0029_alter_beautician_wallet_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="beautician",
            name="bio",
            field=models.CharField(default="", max_length=200),
        ),
    ]
