# Generated by Django 4.2.4 on 2023-10-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0030_beautician_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beautician",
            name="bio",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
