# Generated by Django 4.2.4 on 2023-09-14 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0013_studio"),
        ("customers", "0003_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="studio",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="beautician.studio",
            ),
            preserve_default=False,
        ),
    ]
