# Generated by Django 4.2.4 on 2023-09-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_appointment_studio"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="isblocked",
            field=models.CharField(default="False", max_length=200),
        ),
    ]
