# Generated by Django 4.2.4 on 2023-09-18 10:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0019_alter_beautician_expertin_fee"),
        ("customers", "0005_customer_isblocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="booked_timing",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="beautician.servicefees",
            ),
            preserve_default=False,
        ),
    ]
