# Generated by Django 4.2.4 on 2023-10-18 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beautician", "0028_alter_beautician_appointment_count"),
        ("customers", "0010_appointment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavouriteStylists",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beautician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="beautician.beautician",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
            ],
        ),
    ]
