# Generated by Django 4.2.4 on 2023-10-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0015_alter_workshopbooking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshop",
            name="status",
            field=models.CharField(default="To be conducted", max_length=200),
        ),
    ]
