# Generated by Django 4.2.4 on 2023-10-23 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0017_rename_date_workshop_conducting_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkshopLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link_id", models.CharField(max_length=200)),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.workshop",
                    ),
                ),
            ],
        ),
    ]
